services:

  web:
    build:
      context: ./app/
    container_name: backend
    command: >
      sh -c "python3 manage.py makemigrations && 
      python3 manage.py migrate && 
      python3 su.py && 
      gunicorn config.wsgi:application -b 0.0.0.0:8000 --workers 2 --threads 4"
    volumes:
      - static_files:/usr/src/app/staticfiles
    expose:
      - 8000
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  static_files: