services:

  web:
    build:
      context: ./app/
    container_name: web
    command: >
      sh -c "python3 manage.py makemigrations && 
      python3 manage.py migrate && 
      python3 su.py && 
      python3 server.py"
    expose:
      - 8000
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"