# Generated by Django 4.2.6 on 2023-10-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Товар')),
                ('total', models.IntegerField(verbose_name='Sum')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('customer', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='process.customer')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='item',
            field=models.ManyToManyField(related_name='items', to='process.product'),
        ),
    ]
