# Generated by Django 4.2.6 on 2023-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='item',
            field=models.ManyToManyField(related_name='customers', to='process.product'),
        ),
    ]
